services:
  demo-echo:
    image: hashicorp/http-echo:1.0.0
    command:
      - -listen
      - :8080
      - -text
      - "Hello from demo"
    volumes:
      - demo-data:/var/demo-data
    labels:
      backrest.enable: "true"
      backrest.hooks.template: "simple-stop-start"
      backrest.repo: "sample-repo"
      backrest.schedule: "15 2 * * *"
      backrest.paths.include: "/var/demo-data"
      backrest.keep: "daily=7,weekly=4"
      backrest.pre: "echo quiesce-start"
      backrest.post: "echo quiesce-end"

  demo-echo-lite:
    image: hashicorp/http-echo:1.0.0
    command:
      - -listen
      - :8081
      - -text
      - "Hello from demo-lite"
    volumes:
      - demo-lite-data:/srv/data
    labels:
      backrest.enable: "true"

  sidecar:
    build:
      context: .
      dockerfile: Dockerfile
    image: backrest-sidecar:dev
    environment:
      BACKREST_CONFIG: /etc/backrest/${CONFIG_FILE:-example-sidecar.config.json}
    volumes:
      - ${CONFIG_DIR:-./testdata}:/etc/backrest:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/docker:/var/lib/docker:ro
    command:
      - daemon
      - --config
      - /etc/backrest/config.json
      - --with-events
      - --apply

volumes:
  demo-data:
  demo-lite-data:
